In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df_order_items = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/order_items.csv')

In [ ]:
df_order_items.head()

,order_item_id,order_id,product_id,quantity,unit_price_at_sale,line_total
0,item_0000001,ord_000001,prod_01446,4,16951.04,67804.16
1,item_0000002,ord_000002,prod_04562,5,1449.13,7245.65
2,item_0000003,ord_000002,prod_04575,1,782.99,782.99
3,item_0000004,ord_000003,prod_03437,3,219.07,657.21
4,item_0000005,ord_000003,prod_03429,1,2231.91,2231.91

In [ ]:
df_order_items.shape

(919204, 6)

In [ ]:
df_order_items.count()

order_item_id         919204
order_id              919204
product_id            919204
quantity              919204
unit_price_at_sale    919204
line_total            919204
dtype: int64

In [ ]:
df_order_items.isnull().sum()

order_item_id         0
order_id              0
product_id            0
quantity              0
unit_price_at_sale    0
line_total            0
dtype: int64

In [ ]:
df_order_items.dtypes

order_item_id          object
order_id               object
product_id             object
quantity                int64
unit_price_at_sale    float64
line_total            float64
dtype: object

In [ ]:
duplicated_reviews = df_order_items[df_order_items["order_item_id"].duplicated(keep=False)]
duplicated_reviews.sort_values("order_item_id")

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price_at_sale, line_total]
Index: []

In [ ]:
df_order_items.nunique()

order_item_id         919204
order_id              400000
product_id              5031
quantity                   5
unit_price_at_sale    113250
line_total            397161
dtype: int64

In [ ]:
df_order_items.to_csv('df_order_items.csv', index=False)