In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

import pandas as pd
df_date = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/date_dim_helper.csv')

In [ ]:
df_date.shape

(2557, 10)

In [ ]:
df_date.head()

,date_id,full_date,day_of_week,day_number,month_number,month_name,quarter,year,is_weekend,is_np_holiday
0,1,1/1/2019,Tuesday,1,1,January,Q1,2019,0,0
1,2,1/2/2019,Wednesday,2,1,January,Q1,2019,0,0
2,3,1/3/2019,Thursday,3,1,January,Q1,2019,0,0
3,4,1/4/2019,Friday,4,1,January,Q1,2019,0,0
4,5,1/5/2019,Saturday,5,1,January,Q1,2019,1,0

In [ ]:
df_date.count()

date_id          2557
full_date        2557
day_of_week      2557
day_number       2557
month_number     2557
month_name       2557
quarter          2557
year             2557
is_weekend       2557
is_np_holiday    2557
dtype: int64

In [ ]:
df_date.dtypes

date_id           int64
full_date        object
day_of_week      object
day_number        int64
month_number      int64
month_name       object
quarter          object
year              int64
is_weekend        int64
is_np_holiday     int64
dtype: object

In [ ]:
duplicated_reviews = df_date[df_date["date_id"].duplicated(keep=False)]
duplicated_reviews.sort_values("date_id")

Empty DataFrame
Columns: [date_id, full_date, day_of_week, day_number, month_number, month_name, quarter, year, is_weekend, is_np_holiday]
Index: []

In [ ]:
df_date["full_date"] = pd.to_datetime(df_date["full_date"], errors='coerce')

In [ ]:
df_date.dtypes

date_id                   int64
full_date        datetime64[ns]
day_of_week              object
day_number                int64
month_number              int64
month_name               object
quarter                  object
year                      int64
is_weekend                int64
is_np_holiday             int64
dtype: object

In [ ]:
df_date.head(100)

,date_id,full_date,day_of_week,day_number,month_number,month_name,quarter,year,is_weekend,is_np_holiday
0,1,2019-01-01,Tuesday,1,1,January,Q1,2019,0,0
1,2,2019-01-02,Wednesday,2,1,January,Q1,2019,0,0
2,3,2019-01-03,Thursday,3,1,January,Q1,2019,0,0
3,4,2019-01-04,Friday,4,1,January,Q1,2019,0,0
4,5,2019-01-05,Saturday,5,1,January,Q1,2019,1,0
...,...,...,...,...,...,...,...,...,...,...
95,96,2019-04-06,Saturday,6,4,April,Q2,2019,1,0
96,97,2019-04-07,Sunday,7,4,April,Q2,2019,1,0
97,98,2019-04-08,Monday,8,4,April,Q2,2019,0,0
98,99,2019-04-09,Tuesday,9,4,April,Q2,2019,0,0
99,100,2019-04-10,Wednesday,10,4,April,Q2,2019,0,0

In [ ]:
df_date.isnull().sum()

date_id          0
full_date        0
day_of_week      0
day_number       0
month_number     0
month_name       0
quarter          0
year             0
is_weekend       0
is_np_holiday    0
dtype: int64

In [ ]:
df_date['full_date'].nunique()

2557

In [ ]:
df_date.nunique()

date_id          2557
full_date        2557
day_of_week         7
day_number         31
month_number       12
month_name         12
quarter             4
year                7
is_weekend          2
is_np_holiday       2
dtype: int64

In [ ]:
df_date['day_of_week'].unique()

array(['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
       'Monday'], dtype=object)

In [ ]:
df_date['day_number'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
df_date['month_number'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
df_date['month_name'].unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype=object)

In [ ]:
df_date['quarter'].unique()

array(['Q1', 'Q2', 'Q3', 'Q4'], dtype=object)

In [ ]:
df_date['year'].unique()

array([2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [ ]:
df_date['is_weekend'].unique()

array([0, 1])

In [ ]:
df_date['is_np_holiday'].unique()

array([0, 1])

In [ ]:
df_date.to_csv('date_dim_helper.csv', index=False)

In [ ]:
import pandas as pd
df_sup = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/suppliers.csv')

In [ ]:
df_sup.columns

Index(['supplier_id', 'supplier_name', 'country', 'contact_email',
       'contract_start'],
      dtype='object')

In [ ]:
df_cust = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/customers.csv')
df_cust.columns

Index(['customer_id', 'customer_name', 'email', 'city', 'state_province',
       'country', 'customer_segment', 'registration_date', 'age_group'],
      dtype='object')

In [ ]:
duplicate_count = df_cust.duplicated(subset=['email']).sum()
duplicate_emails = df_cust[df_cust.duplicated(subset=['email'], keep=False)]
print(f"Found {duplicate_count} duplicate email entries.")
print("\nRows with duplicate emails:")
duplicate_emails[['customer_id', 'customer_name', 'email']].sort_values(by='email').head()

Found 2152 duplicate email entries.

Rows with duplicate emails:

        customer_id customer_name                       email
80653   cust_080654    Ajay Rijal     ajay.rijal486@gmail.com
104561  cust_104562    Ajay Rijal     ajay.rijal486@gmail.com
52864   cust_052865   Akash Ghosh  akash.ghosh972@hotmail.com
65266   cust_065267   Akash Ghosh  akash.ghosh972@hotmail.com
89968   cust_089969   Aman Mishra    aman.mishra194@yahoo.com

In [ ]:
df_cust.dtypes

customer_id          object
customer_name        object
email                object
city                 object
state_province       object
country              object
customer_segment     object
registration_date    object
age_group            object
dtype: object

In [ ]:
import pandas as pd

email_regex = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'

is_valid = df_cust['email'].str.contains(email_regex, regex=True, na=False)

invalid_emails = df_cust[~is_valid]

print(f"Total invalid emails found: {len(invalid_emails)}")
invalid_emails.head()

Total invalid emails found: 175

,customer_id,customer_name,email,city,state_province,country,customer_segment,registration_date,age_group
833,cust_000834,Lalitha De Silva,lalitha.de silva5@outlook.com,Kandy,Central Province,Sri Lanka,Retail,2020-11-29,26-35
2527,cust_002528,Hasaranga De Silva,hasaranga.de silva532@yahoo.com,Colombo,Western Province,Sri Lanka,Wholesale,2018-06-13,51+
3623,cust_003624,Sanath De Silva,sanath.de silva340@yahoo.com,Galle,Southern Province,Sri Lanka,Wholesale,2023-04-19,51+
3692,cust_003693,Dinesh De Silva,dinesh.de silva458@outlook.com,Kandy,Central Province,Sri Lanka,Retail,2023-12-03,51+
4656,cust_004657,Subashini De Silva,subashini.de silva885@yahoo.com,Colombo,Western Province,Sri Lanka,Wholesale,2023-07-08,51+

In [ ]:
df_prod = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/products.csv')
df_prod.columns

Index(['product_id', 'product_name', 'category', 'subcategory', 'unit_price',
       'supplier_id', 'weight_kg', 'is_active'],
      dtype='object')

In [ ]:
# 1. Filter for rows where unit_price is less than 0
negative_prices = df_prod[df_prod['unit_price'] <= 0.0]

print(f"Found {len(negative_prices)} products with negative prices:")
negative_prices[['product_id', 'product_name', 'unit_price']]

Found 30 products with negative prices:

      product_id                 product_name  unit_price
170   prod_00171            SmartPro Max Plus         0.0
186   prod_00187              DualSIM Pro Air         0.0
235   prod_00236             FlexiPhone 5G XL         0.0
911   prod_00912        Salwar Kameez Set Neo         0.0
944   prod_00945        Tank Top Cotton Ultra         0.0
1452  prod_01453      Coffee Table Glass Mini         0.0
1465  prod_01466            Water Purifier RO         0.0
1470  prod_01471      Pressure Cooker 5L Plus         0.0
1519  prod_01520  Non-Stick Cookware Set 2023         0.0
1529  prod_01530    Non-Stick Cookware Set V2         0.0
1759  prod_01760       Compost Bin Kitchen XL         0.0
1842  prod_01843     Pillow Memory Foam Elite         0.0
1896  prod_01897       Cushion Cover Set Mini         0.0
2182  prod_02183   Business Strategy 101 Lite         0.0
2256  prod_02257       Leadership Lessons Neo         0.0
2277  prod_02278             Physics Workbook         0.0
2353  prod_02354    Statistics Textbook Ultra         0.0
2612  prod_02613         Pull-Up Bar Door Pro         0.0
2977  prod_02978        Running Hat Visor New         0.0
2994  prod_02995   Running Armband Phone Mini         0.0
3247  prod_03248         Toner Hydrating Rose         0.0
3474  prod_03475        Probiotics Daily Core         0.0
3483  prod_03484      BCAA Recovery Powder SE         0.0
3552  prod_03553       Pre-Workout Energy Neo         0.0
3624  prod_03625      Hair Clip Set Metal New         0.0
3751  prod_03752    Diffuser Ultrasonic Elite         0.0
4254  prod_04255         Hula Hoop Glow Ultra         0.0
4525  prod_04526           Sketch Pad A3 Plus         0.0
4692  prod_04693            Orange Juice Pack         0.0
4726  prod_04727          Chiya Masala Tea XL         0.0

In [ ]:
adf_prod.dtypes

product_id       object
product_name     object
category         object
subcategory      object
unit_price      float64
supplier_id      object
weight_kg       float64
is_active         int64
dtype: object

In [ ]:
df_ord = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/orders.csv')
df_ord.columns

Index(['order_id', 'customer_id', 'order_date', 'bs_year', 'order_status',
       'payment_method', 'shipping_city', 'shipping_country', 'discount_pct'],
      dtype='object')

In [ ]:
df_ord.dtypes

order_id             object
customer_id          object
order_date           object
bs_year               int64
order_status         object
payment_method       object
shipping_city        object
shipping_country     object
discount_pct        float64
dtype: object

In [ ]:
df_ord_itm = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/order_items.csv')
df_ord_itm.columns

Index(['order_item_id', 'order_id', 'product_id', 'quantity',
       'unit_price_at_sale', 'line_total'],
      dtype='object')

In [ ]:
# 1. Filter for rows where unit_price is less than 0
negative_prices = df_ord_itm[df_ord_itm['unit_price_at_sale'] <= 0.0]

# 2. Check the results
if negative_prices.empty:
    print("All good! No negative unit prices found.")
else:
    print(f"Alert: Found {len(negative_prices)} products with negative prices:")
    print(negative_prices[['product_id', 'product_name', 'unit_price']])

All good! No negative unit prices found.

In [ ]:

calculated_total = (df_ord_itm['quantity'] * df_ord_itm['unit_price_at_sale']).round(2)
mismatch_mask = calculated_total != df_ord_itm['line_total'].round(2)
mismatched_rows = df_ord_itm[mismatch_mask].copy()

mismatched_rows['expected_total'] = calculated_total
mismatched_rows['difference'] = mismatched_rows['line_total'] - mismatched_rows['expected_total']

print(f"Found {len(mismatched_rows)} rows with calculation errors:")
mismatched_rows.head()

Found 400 rows with calculation errors:

,order_item_id,order_id,product_id,quantity,unit_price_at_sale,line_total,expected_total,difference
5410,item_0005411,ord_002487,prod_04675,5,1015.43,6243.15,5077.15,1166.00
5561,item_0005562,ord_002563,prod_01715,1,8807.25,9411.14,8807.25,603.89
17385,item_0017386,ord_007992,prod_01202,3,4289.18,15769.72,12867.54,2902.18
20516,item_0020517,ord_009414,prod_01925,4,18738.37,91920.74,74953.48,16967.26
21544,item_0021545,ord_009888,prod_00143,2,29941.34,68065.65,59882.68,8182.97

In [ ]:
df_ord_itm.dtypes

order_item_id          object
order_id               object
product_id             object
quantity                int64
unit_price_at_sale    float64
line_total            float64
dtype: object

In [ ]:
df_rev = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/reviews.csv')
df_rev.columns

Index(['review_id', 'order_id', 'product_id', 'review_score', 'review_date',
       'review_text', 'review_length_chars'],
      dtype='object')

In [ ]:
df_rev.dtypes

review_id               object
order_id                object
product_id              object
review_score           float64
review_date             object
review_text             object
review_length_chars      int64
dtype: object

In [ ]:
df_date = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/date_dim_helper.csv')
df_date.columns

Index(['date_id', 'full_date', 'day_of_week', 'day_number', 'month_number',
       'month_name', 'quarter', 'year', 'is_weekend', 'is_np_holiday'],
      dtype='object')

In [ ]:
df_date.dtypes

date_id           int64
full_date        object
day_of_week      object
day_number        int64
month_number      int64
month_name       object
quarter          object
year              int64
is_weekend        int64
is_np_holiday     int64
dtype: object

In [ ]:
df_cust = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/artifacts/customers_cleaned.csv')
df_cust.columns

Index(['customer_id', 'customer_name', 'email', 'city', 'state_province',
       'country', 'customer_segment', 'registration_date', 'age_group'],
      dtype='object')

In [ ]:
df_ord_itm = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/artifacts/order_items_cleaned.csv')
df_ord_itm.columns

Index(['order_item_id', 'order_id', 'product_id', 'quantity',
       'unit_price_at_sale', 'line_total'],
      dtype='object')

In [ ]:
print('customer_id' in df_ord.columns)
print('customer_id' in df_cust.columns)

True
True

In [ ]:
orphans = df_ord[~df_ord['customer_id'].isin(df_cust['customer_id'])]
missing_ids = orphans['customer_id'].unique()

print(f"Total problematic rows in Orders: {len(orphans)}")
print(f"Number of unique Customer IDs missing: {len(missing_ids)}")
print("\nFirst few missing Customer IDs:")

print(missing_ids)

Total problematic rows in Orders: 1202
Number of unique Customer IDs missing: 1200

First few missing Customer IDs:
['cust_120339' 'cust_120330' 'cust_120204' ... 'cust_120150' 'cust_120779'
 'cust_121079']

In [ ]:
placeholder_customers = pd.DataFrame({
    'customer_id': missing_ids,
    'customer_name': 'Unknown Customer',
    'email': 'unknown@domain.com',
    'city': 'Unknown',
    'state_province': 'Unknown',
    'country': 'Unknown',
    'customer_segment': 'Unknown',
    'registration_date': "2020-08-03",
    'age_group': 'Unknown'
})

In [ ]:
df_cust = pd.concat([df_cust, placeholder_customers], ignore_index=True)

In [ ]:
df_cust.shape

(121200, 9)

In [ ]:
# Re-run orphan check
orphans_after = df_ord[~df_ord['customer_id'].isin(df_cust['customer_id'])]

print("Remaining orphan rows:", len(orphans_after))

Remaining orphan rows: 0

In [ ]:
df_cust.to_csv('customers.csv', index=False)

In [ ]:
df_products = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/artifacts/products_cleaned.csv')

In [ ]:
df_products.columns

Index(['product_id', 'product_name', 'category', 'subcategory', 'unit_price',
       'supplier_id', 'weight_kg', 'is_active'],
      dtype='object')

In [ ]:
duplicated_products = df_products[df_products["product_id"].duplicated(keep=False)]
duplicated_products

Empty DataFrame
Columns: [product_id, product_name, category, subcategory, unit_price, supplier_id, weight_kg, is_active]
Index: []

In [ ]:
df_order_items = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/artifacts/order_items_cleaned.csv')
df_products = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/artifacts/products_cleaned.csv')

In [ ]:
df_order_items.columns

Index(['order_item_id', 'order_id', 'product_id', 'quantity',
       'unit_price_at_sale', 'line_total'],
      dtype='object')

In [ ]:
df_products.columns

Index(['product_id', 'product_name', 'category', 'subcategory', 'unit_price',
       'supplier_id', 'weight_kg', 'is_active'],
      dtype='object')

In [ ]:
orphans = df_order_items[~df_order_items['product_id'].isin(df_products['product_id'])]
missing_ids = orphans['product_id'].unique()

print(f"Total problematic rows in Orders_Items: {len(orphans)}")
print(f"Number of unique Product IDs missing: {len(missing_ids)}")
print("\nFirst few missing Product IDs:")

print(missing_ids)

Total problematic rows in Orders_Items: 250
Number of unique Product IDs missing: 250

First few missing Product IDs:
['prod_05239' 'prod_05184' 'prod_05110' 'prod_05120' 'prod_05135'
 'prod_05016' 'prod_05071' 'prod_05124' 'prod_05218' 'prod_05109'
 'prod_05044' 'prod_05157' 'prod_05246' 'prod_05222' 'prod_05076'
 'prod_05107' 'prod_05198' 'prod_05003' 'prod_05088' 'prod_05231'
 'prod_05147' 'prod_05204' 'prod_05037' 'prod_05086' 'prod_05154'
 'prod_05114' 'prod_05167' 'prod_05188' 'prod_05012' 'prod_05102'
 'prod_05035' 'prod_05133' 'prod_05015' 'prod_05155' 'prod_05173'
 'prod_05159' 'prod_05144' 'prod_05229' 'prod_05128' 'prod_05243'
 'prod_05046' 'prod_05115' 'prod_05094' 'prod_05051' 'prod_05067'
 'prod_05031' 'prod_05064' 'prod_05020' 'prod_05203' 'prod_05002'
 'prod_05080' 'prod_05052' 'prod_05165' 'prod_05140' 'prod_05030'
 'prod_05092' 'prod_05059' 'prod_05179' 'prod_05090' 'prod_05186'
 'prod_05022' 'prod_05116' 'prod_05206' 'prod_05005' 'prod_05202'
 'prod_05025' 'prod_05196' 'prod_05217' 'prod_05149' 'prod_05085'
 'prod_05111' 'prod_05183' 'prod_05210' 'prod_05068' 'prod_05113'
 'prod_05054' 'prod_05024' 'prod_05065' 'prod_05237' 'prod_05151'
 'prod_05050' 'prod_05075' 'prod_05099' 'prod_05134' 'prod_05014'
 'prod_05207' 'prod_05205' 'prod_05040' 'prod_05010' 'prod_05224'
 'prod_05074' 'prod_05201' 'prod_05219' 'prod_05170' 'prod_05146'
 'prod_05053' 'prod_05021' 'prod_05195' 'prod_05160' 'prod_05043'
 'prod_05176' 'prod_05143' 'prod_05123' 'prod_05208' 'prod_05013'
 'prod_05131' 'prod_05125' 'prod_05227' 'prod_05142' 'prod_05129'
 'prod_05045' 'prod_05078' 'prod_05011' 'prod_05164' 'prod_05197'
 'prod_05001' 'prod_05009' 'prod_05138' 'prod_05250' 'prod_05072'
 'prod_05095' 'prod_05036' 'prod_05141' 'prod_05221' 'prod_05027'
 'prod_05100' 'prod_05083' 'prod_05081' 'prod_05191' 'prod_05180'
 'prod_05062' 'prod_05242' 'prod_05087' 'prod_05161' 'prod_05057'
 'prod_05023' 'prod_05182' 'prod_05077' 'prod_05105' 'prod_05033'
 'prod_05234' 'prod_05101' 'prod_05235' 'prod_05127' 'prod_05047'
 'prod_05163' 'prod_05130' 'prod_05241' 'prod_05177' 'prod_05089'
 'prod_05174' 'prod_05096' 'prod_05061' 'prod_05168' 'prod_05132'
 'prod_05028' 'prod_05209' 'prod_05049' 'prod_05244' 'prod_05156'
 'prod_05230' 'prod_05172' 'prod_05232' 'prod_05084' 'prod_05112'
 'prod_05056' 'prod_05121' 'prod_05103' 'prod_05200' 'prod_05225'
 'prod_05245' 'prod_05007' 'prod_05212' 'prod_05008' 'prod_05223'
 'prod_05082' 'prod_05106' 'prod_05017' 'prod_05097' 'prod_05122'
 'prod_05032' 'prod_05048' 'prod_05236' 'prod_05108' 'prod_05158'
 'prod_05073' 'prod_05166' 'prod_05214' 'prod_05034' 'prod_05104'
 'prod_05175' 'prod_05153' 'prod_05026' 'prod_05194' 'prod_05215'
 'prod_05060' 'prod_05098' 'prod_05199' 'prod_05226' 'prod_05220'
 'prod_05041' 'prod_05093' 'prod_05190' 'prod_05058' 'prod_05150'
 'prod_05248' 'prod_05137' 'prod_05233' 'prod_05118' 'prod_05187'
 'prod_05240' 'prod_05247' 'prod_05018' 'prod_05069' 'prod_05249'
 'prod_05181' 'prod_05139' 'prod_05019' 'prod_05228' 'prod_05189'
 'prod_05079' 'prod_05162' 'prod_05211' 'prod_05117' 'prod_05091'
 'prod_05238' 'prod_05171' 'prod_05004' 'prod_05038' 'prod_05185'
 'prod_05145' 'prod_05213' 'prod_05006' 'prod_05193' 'prod_05126'
 'prod_05039' 'prod_05063' 'prod_05152' 'prod_05029' 'prod_05178'
 'prod_05136' 'prod_05148' 'prod_05119' 'prod_05216' 'prod_05169'
 'prod_05192' 'prod_05055' 'prod_05070' 'prod_05042' 'prod_05066']

In [ ]:
import pandas as pd

placeholder_products = pd.DataFrame({
    'product_id': missing_ids,
    'product_name': 'Unknown Product',
    'category': 'Unknown',
    'subcategory': 'Unknown',
    'unit_price': 0.0,
    'supplier_id': "supp_201",
    'weight_kg': 0.0,
    'is_active': False
})

In [ ]:
df_products = pd.concat([df_products, placeholder_products], ignore_index=True)

In [ ]:
orphans_after = df_order_items[
    ~df_order_items['product_id'].isin(df_products['product_id'])
]

print("Remaining orphan rows:", len(orphans_after))

Remaining orphan rows: 0

In [ ]:
df_products.to_csv('products_cleaned_250_rows_added_supp_added.csv', index=False)

In [ ]:
df_products.shape

(5250, 8)

In [ ]:
df_review = pd.read_csv('/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/reviews.csv')
#

In [ ]:
df_review.head()

,review_id,order_id,product_id,review_score,review_date,review_text,review_length_chars
0,rev_000001,ord_200369,prod_01620,3.0,1/6/2024,Average quality. The Non-Stick Cookware Set 20...,214
1,rev_000002,ord_306978,prod_01067,4.0,12/19/2023,Amazing product! Better than expected. The bui...,146
2,rev_000003,ord_078396,prod_04954,5.0,10/29/2022,Fantastic purchase. The quality exceeds the pr...,213
3,rev_000004,ord_231351,prod_00296,4.0,4/26/2022,Perfect for my needs. Easy to use and great qu...,185
4,rev_000005,ord_244947,prod_02596,5.0,12/2/2021,Amazing product! Better than expected. The bui...,149

In [ ]:
orphans = df_review[~df_review['product_id'].isin(df_products['product_id'])]
missing_ids = orphans['product_id'].unique()

print(f"Total problematic rows in Reviews: {len(orphans)}")
print(f"Number of unique Product IDs missing: {len(missing_ids)}")
print("\nFirst few missing Product IDs:")

print(missing_ids)

Total problematic rows in Reviews: 0
Number of unique Product IDs missing: 0

First few missing Product IDs:
[]

In [ ]:
orphans = df_review[~df_review['order_id'].isin(df_ord['order_id'])]
missing_ids = orphans['order_id'].unique()

print(f"Total problematic rows in Reviews: {len(orphans)}")
print(f"Number of unique Order IDs missing: {len(missing_ids)}")
print("\nFirst few missing Order IDs:")

print(missing_ids)

Total problematic rows in Reviews: 0
Number of unique Order IDs missing: 0

First few missing Order IDs:
[]