In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
suppliers_df = pd.read_csv("/content/drive/MyDrive/BigDataAndDataMiningCoursework/








































































































































































































































































































































































































+++++++++++++++++++++++++++++++++/suppliers.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/suppliers.csv'

In [ ]:
suppliers_df.info()

In [ ]:
# This returns all rows where the customer_id is a repeat
duplicates = suppliers_df[df_customer.duplicated('supplier_id', keep=False)]

# Sorting helps you see the pairs side-by-side
duplicates.sort_values(by='supplier_id')

NameError: name 'suppliers_df' is not defined

In [ ]:
suppliers_df.isnull().sum()

supplier_id       0
supplier_name     0
country           0
contact_email     0
contract_start    0
dtype: int64

In [ ]:
duplicated_reviews = suppliers_df[suppliers_df["supplier_id"].duplicated(keep=False)]
duplicated_reviews.sort_values("supplier_id")

Empty DataFrame
Columns: [supplier_id, supplier_name, country, contact_email, contract_start]
Index: []

In [ ]:
suppliers_df

,supplier_id,supplier_name,country,contact_email,contract_start
0,supp_001,Himalayan Traders Pvt Ltd,Nepal,contact@himalayantra1.com,4/1/2016
1,supp_002,Sagarmatha Suppliers,Nepal,contact@sagarmathasu2.com,4/13/2015
2,supp_003,Nepal Commerce Hub,Nepal,contact@nepalcommerc3.com,1/31/2018
3,supp_004,Kathmandu Wholesale Co,Nepal,contact@kathmanduwho4.com,9/30/2017
4,supp_005,Lumbini Trading House,Nepal,contact@lumbinitradi5.com,7/3/2017
...,...,...,...,...,...
195,supp_196,Dubai Wholesale Hub Branch 17,UAE,contact@dubaiwholesa196.com,3/18/2021
196,supp_197,Abu Dhabi Trading Corp Branch 18,UAE,contact@abudhabitrad197.com,7/31/2017
197,supp_198,Sharjah Supply Chain Branch 19,UAE,contact@sharjahsuppl198.com,8/7/2021
198,supp_199,Emirates Commerce Ltd Branch 20,UAE,contact@emiratescomm199.com,6/21/2017
199,supp_200,Gulf Trading House Branch 21,UAE,contact@gulftradingh200.com,1/30/2015

In [ ]:
suppliers_df.duplicated().sum()

np.int64(0)

In [ ]:
suppliers_df["contract_start"] = pd.to_datetime(suppliers_df["contract_start"], errors='coerce')

In [ ]:
suppliers_df

,supplier_id,supplier_name,country,contact_email,contract_start
0,supp_001,Himalayan Traders Pvt Ltd,Nepal,contact@himalayantra1.com,2016-04-01
1,supp_002,Sagarmatha Suppliers,Nepal,contact@sagarmathasu2.com,2015-04-13
2,supp_003,Nepal Commerce Hub,Nepal,contact@nepalcommerc3.com,2018-01-31
3,supp_004,Kathmandu Wholesale Co,Nepal,contact@kathmanduwho4.com,2017-09-30
4,supp_005,Lumbini Trading House,Nepal,contact@lumbinitradi5.com,2017-07-03
...,...,...,...,...,...
195,supp_196,Dubai Wholesale Hub Branch 17,UAE,contact@dubaiwholesa196.com,2021-03-18
196,supp_197,Abu Dhabi Trading Corp Branch 18,UAE,contact@abudhabitrad197.com,2017-07-31
197,supp_198,Sharjah Supply Chain Branch 19,UAE,contact@sharjahsuppl198.com,2021-08-07
198,supp_199,Emirates Commerce Ltd Branch 20,UAE,contact@emiratescomm199.com,2017-06-21
199,supp_200,Gulf Trading House Branch 21,UAE,contact@gulftradingh200.com,2015-01-30

In [ ]:
suppliers_df.to_csv('suppliers.csv', index=False)
print("df_product exported successfully to 'products.csv'")

df_product exported successfully to 'products.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')