In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
orders = pd.read_csv("/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/orders.csv")

In [ ]:
orders

,order_id,customer_id,order_date,bs_year,order_status,payment_method,shipping_city,shipping_country,discount_pct
0,ord_000001,cust_049923,11/18/2023,2080,Cancelled,Connect IPS,Hetauda,Nepal,0.02
1,ord_000002,cust_008684,5/17/2023,2080,Shipped,Connect IPS,Kolkata,India,0.22
2,ord_000003,cust_067594,7/10/2022,2079,Returned,Cash on Delivery,Pokhara,Nepal,0.21
3,ord_000004,cust_055649,7/25/2023,2080,Delivered,Cash on Delivery,Butwal,Nepal,0.05
4,ord_000005,cust_038657,9/13/2020,2077,Delivered,Khalti,Birgunj,Nepal,0.02
...,...,...,...,...,...,...,...,...,...
400495,ord_075551,cust_117139,12/7/2023,2080,Shipped,Cash on Delivery,Kathmandu,Nepal,0.21
400496,ord_365484,cust_102935,7/20/2022,2079,Delivered,Khalti,Kathmandu,Nepal,0.19
400497,ord_398040,cust_087679,12/6/2022,2079,Delivered,eSewa,Kathmandu,Nepal,0.21
400498,ord_324508,cust_046837,7/20/2022,2079,Cancelled,Connect IPS,Kathmandu,Nepal,0.09
400499,ord_390824,cust_039049,12/17/2022,2079,Delivered,eSewa,Biratnagar,Nepal,0.13

In [ ]:
orders.isnull().sum()

order_id              0
customer_id           0
order_date            0
bs_year               0
order_status          0
payment_method        0
shipping_city         0
shipping_country      0
discount_pct        300
dtype: int64

In [ ]:
orders["payment_method"].unique()

array(['Connect IPS', 'Cash on Delivery', 'Khalti', 'eSewa'], dtype=object)

In [ ]:
orders["shipping_country"].unique()

array(['Nepal', 'India', 'Bangladesh', 'Sri Lanka'], dtype=object)

In [ ]:
orders["shipping_city"].unique()

array(['Hetauda', 'Kolkata', 'Pokhara', 'Butwal', 'Birgunj', 'Lalitpur',
       'Biratnagar', 'Kathmandu', 'Bharatpur', 'Varanasi', 'Chittagong',
       'Sylhet', 'Lucknow', 'Nepalgunj', 'Jaffna', 'Khulna', 'Galle',
       'Dharan', 'Colombo', 'Bangalore', 'Dhaka', 'Hyderabad', 'Rajshahi',
       'Mumbai', 'Delhi', 'Kandy', 'Patna', 'Jaipur', 'Chennai'],
      dtype=object)

In [ ]:
orders["order_status"].unique()

array(['Cancelled', 'Shipped', 'Returned', 'Delivered'], dtype=object)

In [ ]:
orders.dtypes

order_id             object
customer_id          object
order_date           object
bs_year               int64
order_status         object
payment_method       object
shipping_city        object
shipping_country     object
discount_pct        float64
dtype: object

In [ ]:
orders["order_date"] = pd.to_datetime(orders["order_date"], errors='coerce')

In [ ]:
orders

,order_id,customer_id,order_date,bs_year,order_status,payment_method,shipping_city,shipping_country,discount_pct
0,ord_000001,cust_049923,2023-11-18,2080,Cancelled,Connect IPS,Hetauda,Nepal,0.02
1,ord_000002,cust_008684,2023-05-17,2080,Shipped,Connect IPS,Kolkata,India,0.22
2,ord_000003,cust_067594,2022-07-10,2079,Returned,Cash on Delivery,Pokhara,Nepal,0.21
3,ord_000004,cust_055649,2023-07-25,2080,Delivered,Cash on Delivery,Butwal,Nepal,0.05
4,ord_000005,cust_038657,2020-09-13,2077,Delivered,Khalti,Birgunj,Nepal,0.02
...,...,...,...,...,...,...,...,...,...
400495,ord_075551,cust_117139,2023-12-07,2080,Shipped,Cash on Delivery,Kathmandu,Nepal,0.21
400496,ord_365484,cust_102935,2022-07-20,2079,Delivered,Khalti,Kathmandu,Nepal,0.19
400497,ord_398040,cust_087679,2022-12-06,2079,Delivered,eSewa,Kathmandu,Nepal,0.21
400498,ord_324508,cust_046837,2022-07-20,2079,Cancelled,Connect IPS,Kathmandu,Nepal,0.09
400499,ord_390824,cust_039049,2022-12-17,2079,Delivered,eSewa,Biratnagar,Nepal,0.13

In [ ]:
null_discounts = orders[orders["discount_pct"].isnull()]

null_discounts

,order_id,customer_id,order_date,bs_year,order_status,payment_method,shipping_city,shipping_country,discount_pct
352,ord_000353,cust_061197,2023-06-27,2080,Shipped,Cash on Delivery,Dhaka,Bangladesh,NaN
1057,ord_001058,cust_088720,2020-11-10,2077,Delivered,eSewa,Kathmandu,Nepal,NaN
1145,ord_001146,cust_079858,2022-08-04,2079,Shipped,eSewa,Lucknow,India,NaN
2914,ord_002915,cust_017590,2023-08-24,2080,Delivered,Connect IPS,Lalitpur,Nepal,NaN
3040,ord_003041,cust_030185,2021-12-06,2078,Delivered,Cash on Delivery,Jaffna,Sri Lanka,NaN
...,...,...,...,...,...,...,...,...,...
393822,ord_393823,cust_069843,2023-10-21,2080,Delivered,Khalti,Hetauda,Nepal,NaN
395594,ord_395595,cust_048342,2021-01-05,2077,Delivered,eSewa,Sylhet,Bangladesh,NaN
395605,ord_395606,cust_086739,2023-04-13,2080,Cancelled,Connect IPS,Rajshahi,Bangladesh,NaN
398268,ord_398269,cust_055371,2020-06-14,2077,Shipped,Khalti,Dharan,Nepal,NaN
398984,ord_398985,cust_113073,2023-11-28,2080,Delivered,Cash on Delivery,Jaipur,India,NaN

In [ ]:
orders["discount_pct"].value_counts()

discount_pct
0.03    16262
0.04    16245
0.21    16165
0.06    16163
0.08    16102
0.24    16094
0.14    16056
0.22    16040
0.11    16025
0.16    16023
0.01    16020
0.10    16010
0.19    15986
0.23    15973
0.17    15954
0.09    15945
0.20    15938
0.18    15933
0.05    15930
0.02    15921
0.13    15918
0.15    15843
0.07    15806
0.12    15798
0.00     8048
0.25     8002
Name: count, dtype: int64

In [ ]:
orders["discount_pct"] = orders["discount_pct"].fillna(0.0)

In [ ]:
null_discounts = orders[orders["discount_pct"].isnull()]

null_discounts

Empty DataFrame
Columns: [order_id, customer_id, order_date, bs_year, order_status, payment_method, shipping_city, shipping_country, discount_pct]
Index: []

In [ ]:
orders.dtypes

order_id                    object
customer_id                 object
order_date          datetime64[ns]
bs_year                      int64
order_status                object
payment_method              object
shipping_city               object
shipping_country            object
discount_pct               float64
dtype: object

In [ ]:
orders.shape

(400500, 9)

In [ ]:
orders["order_id"].unique()

array(['ord_000001', 'ord_000002', 'ord_000003', ..., 'ord_399998',
       'ord_399999', 'ord_400000'], dtype=object)

In [ ]:
orders["order_id"].nunique()

400000

In [ ]:
duplicated_orders = orders[orders["order_id"].duplicated(keep=False)]
print("Number of duplicated records: ", duplicated_orders.shape[0])
print("Sample: \n")
duplicated_orders.sort_values("order_id")

Number of duplicated records:  1000
Sample:

,order_id,customer_id,order_date,bs_year,order_status,payment_method,shipping_city,shipping_country,discount_pct
791,ord_000792,cust_078839,6/29/2021,2078,Shipped,Khalti,Hetauda,Nepal,0.02
400472,ord_000792,cust_078839,6/30/2021,2078,Shipped,Khalti,Hetauda,Nepal,0.02
1380,ord_001381,cust_109127,5/5/2020,2077,Delivered,Cash on Delivery,Kathmandu,Nepal,0.24
400124,ord_001381,cust_109127,5/6/2020,2077,Delivered,Cash on Delivery,Kathmandu,Nepal,0.24
400027,ord_001597,cust_115330,11/16/2023,2080,Shipped,Cash on Delivery,Dharan,Nepal,0.03
...,...,...,...,...,...,...,...,...,...
400187,ord_398513,cust_056549,10/15/2022,2079,Shipped,Cash on Delivery,Biratnagar,Nepal,0.14
398924,ord_398925,cust_110012,7/29/2023,2080,Delivered,Cash on Delivery,Kathmandu,Nepal,0.24
400431,ord_398925,cust_110012,7/30/2023,2080,Delivered,Cash on Delivery,Kathmandu,Nepal,0.24
400493,ord_399212,cust_112642,10/24/2023,2080,Delivered,Cash on Delivery,Kathmandu,Nepal,0.13
399211,ord_399212,cust_112642,10/23/2023,2080,Delivered,Cash on Delivery,Kathmandu,Nepal,0.13

In [ ]:
orders = orders.drop_duplicates(subset=["order_id"], keep='first')
print(f"Remaining duplicates: {orders['order_id'].duplicated().sum()}")

Remaining duplicates: 0

In [ ]:
duplicated_orders = orders[orders["order_id"].duplicated(keep=False)]
duplicated_orders.sort_values("order_id")

Empty DataFrame
Columns: [order_id, customer_id, order_date, bs_year, order_status, payment_method, shipping_city, shipping_country, discount_pct]
Index: []

In [ ]:
orders.nunique()

order_id            400000
customer_id         111887
order_date            1822
bs_year                  6
order_status             4
payment_method           4
shipping_city           29
shipping_country         4
discount_pct            26
dtype: int64

In [ ]:
orders.to_csv('orders.csv', index=False)